### ISSUE TITLE
[Question] How to ssl pinning bypass the new versions of instagram?

### ISSUE THREAD

**Issue by DRVR1** [tanu360/Instagram-SSL-Pinning-Bypass#1]
Hey, i was trying to ssl bypass the new version of instagram (319) with no success, i have some questions about your method for patching this apk, here is my telegram @ian0157 thank you

**Comment by tanu360** [comment]
Hi there,

Greetings! I hope this email finds you well. Regarding your inquiry about
bypassing SSL pinning for the latest Instagram version, I appreciate your
interest in my work. However, due to limited availability these days, I can
only offer paid assistance for such requests.

If you're open to that, feel free to contact me via Telegram ***@***.***) or
through this email. I'd be happy to discuss the details and provide my
services accordingly. Please note that I maintain a professional and formal
approach in such engagements.

Looking forward to hearing from you.

Best regards,
Tanu360

**Comment by wezabronsz** [comment]
Did you managed to find out?

**Comment by tanu360** [comment]
Hi there,

I wanted to let you know that I have successfully bypassed the SSL check in
latest version of Instagram. If you're interested, I can provide you access. Let me know if you're interested!
